[project]
name = "rmstweb"
version = "0.1.0"
description = "RMST Website Project"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "django==5.2.4",
    "django-compressor>=4.5.1",
    "psycopg2>=2.9.10",
    "sendgrid>=6.12.4",
]
